#!/bin/bash
#
# wma_to_mp3
#
# Usage: wma_to_mp3 <directory>
#
# Use FFMpeg to convert a directory of .wma format audio files to .mp3,
#
# (C) L.Pritchard 2012

# Escape if no args
if 
  [ $# -eq 0 ]
then
  echo "Please provide a root directory for the conversions"
  echo "(exiting)"
  exit
fi

# Start with empty list of directories, and populate
dirlist=()

# Add all command-line directories
echo "Passed directories..."
for d in "$@"
do
  echo $d
  if
    [ -d "$1" ]
  then
    dirlist=("${dirlist[@]}" "$d")
  fi
  # Add first level of subdirectories for each passed directory
  for f in "${d%%/}"/*
  do
    if 
      [ -d "$f" ]
    then
      dirlist=("${dirlist[@]}" "$f")
    fi
  done
done

# List directories that will be processed
echo "The following directories will be processed:"
for d in "${dirlist[@]}"
do
  echo $d
done
echo

# Loop over directories and grab filenames
for d in "${dirlist[@]}"
do
  echo "Processing $d"
  echo "Found the following .wma files:"
  filelist=()
  for filename in "$d"/*.wma
  do
    if 
      [ -f "$filename" ]
    then
      filelist=("${filelist[@]}" "$filename")
    fi
  done
  for f in "${filelist[@]}"
  do
    echo $f
  done
  echo "Converting files..."
  for f in "${filelist[@]}"
  do
    o=${f%%.wma}.mp3
    echo "...converting..."
    #cmd="time ffmpeg -i \"${f}\" -vcodec copy -acodec copy -f mp4 -y \"${o}\""
    # Corrects for trouble with timebase
    cmd="time ffmpeg -i "${f}" -f mp3 -y "${o}""
    echo $cmd
    time ffmpeg -i "${f}" -f mp3 -y "${o}"
    #echo "...deleting input avi..."
    #cmd="rm \"${f}\""
    #echo $cmd
    #rm "${f}"
  done
  echo
  echo
done
exit
